[package]
name = "inbox"
version = "0.0.0"
authors = ["Ian Macalinao <ian@aptos.is>"]
license = "Apache-2.0"

[readme]
title = "Inbox by Aptos.is"

[addresses]
inbox_deployer = "0x9cb1dbb8ebfaf55412bdf8259f67be908b2c928fdd9a1c9e94c1434dfc363c79"
inbox = "0xf79945b8d98af4d50f1d9c84a27362d032e48c2c17a3f24e3c81cf4a2a0e06c0"

[dependencies.deployer]
git = "https://github.com/DeployDAO/aptos-deployer.git"
rev = "03eb53be2d1e25d516767581641981f18157a151"
